[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements.txt", 
    "templates/**", 
    "pages/**", 
    "commandments/**",
    "railway.toml",
    "Dockerfile",
]